---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - soap-bubble-operator.soap-bubble-operator.local
  resources:
  - soapbubblemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - soap-bubble-operator.soap-bubble-operator.local
  resources:
  - soapbubblemachines/finalizers
  verbs:
  - update
- apiGroups:
  - soap-bubble-operator.soap-bubble-operator.local
  resources:
  - soapbubblemachines/status
  verbs:
  - get
  - patch
  - update
