# permissions for end users to edit soapbubblemachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: soap-bubble-operator
    app.kubernetes.io/managed-by: kustomize
  name: soapbubblemachine-editor-role
rules:
- apiGroups:
  - soap-bubble-operator.soap-bubble-operator.local
  resources:
  - soapbubblemachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - soap-bubble-operator.soap-bubble-operator.local
  resources:
  - soapbubblemachines/status
  verbs:
  - get
