apiVersion: soap-bubble-operator.soap-bubble-operator.local/v1alpha1
kind: SoapBubbleMachine
metadata:
  labels:
    app.kubernetes.io/name: soap-bubble-operator
    app.kubernetes.io/managed-by: kustomize
    machine/identifier: 0688db36-38d9-46c0-9f6e-abf51903afe8
  name: sample-soap-bubble-machine
spec:
  # The name of the machine
  machineName: sample-soap-bubble-machine
  # The IP address of the the soap bubble machine
  ip: 192.168.1.200
  # The desired state of the bubbles machine
  makeBubbles: true
  # The speed of the bubbles machine
  speed: 100
